# Generated by Django 4.2 on 2023-04-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_categories', models.CharField(choices=[('Mobile', 'Mobile'), ('Camera', 'Camera'), ('Laptop', 'Laptop'), ('Head-phone', 'Head-phone')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
