# Generated by Django 4.2 on 2023-04-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category_alter_product_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_categories',
        ),
    ]
