# Generated by Django 4.2 on 2023-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_category_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_categories',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Camera', 'Camera'), ('Laptop', 'Laptop'), ('Head-phone', 'Head-phone')], max_length=100),
        ),
    ]
