# Generated by Django 4.2 on 2023-04-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_categories',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Camera', 'Camera'), ('Laptop', 'Laptop'), ('Head-phone', 'Head-phone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(upload_to='product_pic/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
