# Generated by Django 4.2 on 2023-05-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_cart_payment_ststus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='payment_ststus',
            new_name='payment_status',
        ),
    ]
