# Generated by Django 4.2 on 2023-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_payment_ststus_cart_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_status',
            field=models.BooleanField(default=False),
        ),
    ]
